### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [theforeman/foreman-infra#1424]
55 hard-coded secrets were found in 27 different scripts.

Script 1: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp
 - Line [56](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp#L56): `ssl_cert=/etc/letsencrypt/live/`
 - Line [57](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp#L57): `ssl_chain=/etc/letsencrypt/live/`
 - Line [58](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp#L58): `ssl_key=/etc/letsencrypt/live/`

Script 2: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/htpasswd.pp
 - Line [11](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/htpasswd.pp#L11): `cryptpasswd=ht_crypt`

Script 3: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/init.pp
 - Line [68](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/init.pp#L68): `user=root`

Script 4: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/letsencrypt.pp
 - Line [11](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/letsencrypt.pp#L11): `user=root`

Script 5: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp
 - Line [48](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp#L48): `ssl_cert=/etc/letsencrypt/live/`
 - Line [49](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp#L49): `ssl_chain=/etc/letsencrypt/live/`
 - Line [50](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp#L50): `ssl_key=/etc/letsencrypt/live/`

Script 6: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/stagingdeb.pp
 - Line [4](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/stagingdeb.pp#L4): `user=freightstage`

Script 7: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/debugs.pp
 - Line [15](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/debugs.pp#L15): `htpasswds=each`

Script 8: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/web.pp
 - Line [50](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/web.pp#L50): `user=website`

Script 9: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/deb.pp
 - Line [4](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/deb.pp#L4): `user=freight`
 - Line [27](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/vhost/deb.pp#L27): `ssh_key_name=rsync_`

Script 10: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/scaleway/manifests/cron.pp
 - Line [5](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/scaleway/manifests/cron.pp#L5): `api_key=na`
 - Line [20](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/scaleway/manifests/cron.pp#L20): `user=root`

Script 11: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/db_config.pp
 - Line [5](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/db_config.pp#L5): `jenkins_user=jenkins`

Script 12: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/mysql.pp
 - Line [16](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/mysql.pp#L16): `mysql_user=foreman`
 - Line [25](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/mysql.pp#L25): `user=foreman`
 - Line [32](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/mysql.pp#L32): `user=foreman`

Script 13: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/postgresql.pp
 - Line [91](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/postgresql.pp#L91): `password_hash=postgresql_password`

Script 14: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/init.pp
 - Line [250](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/init.pp#L250): `user=jenkins`

Script 15: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp
 - Line [4](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp#L4): `gnupg_key=rvm_pkuczynski`
 - Line [6](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp#L6): `key_id=39499bdb`
 - Line [7](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp#L7): `user=root`
 - Line [8](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp#L8): `key_source=https://rvm.io/pkuczynski.asc`
 - Line [9](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/rvm.pp#L9): `key_type=public`

Script 16: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/foreman_debug_rsync/manifests/cron.pp
 - Line [5](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/foreman_debug_rsync/manifests/cron.pp#L5): `user=nobody`

Script 17: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/rbot/manifests/params.pp
 - Line [5](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/rbot/manifests/params.pp#L5): `user=rbot`
 - Line [10](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/rbot/manifests/params.pp#L10): `auth_password=rbotauth`

Script 18: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/uploader_key.pp
 - Line [24](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/uploader_key.pp#L24): `pub_key=ssh_keygen`
 - Line [24](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/uploader_key.pp#L24): `ssh_key_name=public`
 - Line [25](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/uploader_key.pp#L25): `priv_key=ssh_keygen`

Script 19: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/receiver_setup.pp
 - Line [56](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/receiver_setup.pp#L56): `pub_key=ssh_keygen`
 - Line [56](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/receiver_setup.pp#L56): `ssh_key_name=public`

Script 20: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/rsync/uploader_key.pp
 - Line [27](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/rsync/uploader_key.pp#L27): `ssh_key_name=rsync_`

Script 21: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/rsync/receiver_setup.pp
 - Line [38](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secure_ssh/manifests/rsync/receiver_setup.pp#L38): `ssh_key_name=rsync_`

Script 22: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secretsgit/manifests/init.pp
 - Line [18](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/secretsgit/manifests/init.pp#L18): `users=each`

Script 23: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/exim/manifests/init.pp
 - Line [35](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/exim/manifests/init.pp#L35): `tls_certificate=/etc/pki/tls/certs/exim.pem`
 - Line [36](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/exim/manifests/init.pp#L36): `tls_privatekey=/etc/pki/tls/private/exim.pem`
 - Line [42](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/exim/manifests/init.pp#L42): `never_users=root`

Script 24: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp
 - Line [27](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L27): `secret_token=token`
 - Line [28](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L28): `email_password=pass`
 - Line [33](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L33): `username=redmine`
 - Line [76](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L76): `password=postgresql_password`
 - Line [174](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L174): `ssl_cert=/etc/letsencrypt/live/`
 - Line [175](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L175): `ssl_chain=/etc/letsencrypt/live/`
 - Line [176](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/redmine/manifests/init.pp#L176): `ssl_key=/etc/letsencrypt/live/`

Script 25: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/deploy/manifests/init.pp
 - Line [3](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/deploy/manifests/init.pp#L3): `user=deploypuppet`

Script 26: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/prprocessor/manifests/init.pp
 - Line [19](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/prprocessor/manifests/init.pp#L19): `username=prprocessor`
 - Line [132](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/prprocessor/manifests/init.pp#L132): `ssl_cert=/etc/letsencrypt/live/`
 - Line [133](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/prprocessor/manifests/init.pp#L133): `ssl_chain=/etc/letsencrypt/live/`
 - Line [134](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/prprocessor/manifests/init.pp#L134): `ssl_key=/etc/letsencrypt/live/`

Script 27: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/vagrant/manifests/default.pp
 - Line [16](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/vagrant/manifests/default.pp#L16): `username=admin`
 - Line [17](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/vagrant/manifests/default.pp#L17): `password=changeme`

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by ekohl** [comment]
All false positives.
