### ISSUE TITLE
Potential vulnerabilities in Puppet files: Use of HTTP without TLS

### ISSUE THREAD

**Issue by cantebigene** [theforeman/foreman-infra#1425]
31 configurations of HTTP without TLS were found in 6 different scripts.

Script 1: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp
 - Line [10](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/jenkins.pp#L10): `http://localhost:8080/`

Script 2: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp
 - Line [20](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/web/manifests/stats.pp#L20): `http://localhost:3838/`

Script 3: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp
 - Line [18](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L18): `http://ubuntu.osuosl.org/ubuntu/`
 - Line [19](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L19): `deb http://ubuntu.osuosl.org/ubuntu/ bionic main restricted universe\ndeb-src http://ubuntu.osuosl.org/ubuntu/ bionic main restricted universe\n`
 - Line [24](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L24): `http://deb.debian.org/debian`
 - Line [25](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L25): `deb http://deb.debian.org/debian/ buster main non-free contrib\ndeb-src http://deb.debian.org/debian/ buster main non-free contrib\n`
 - Line [30](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L30): `http://ubuntu.osuosl.org/ubuntu/`
 - Line [31](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L31): `deb http://ubuntu.osuosl.org/ubuntu/ focal main restricted universe\ndeb-src http://ubuntu.osuosl.org/ubuntu/ focal main restricted universe\n`
 - Line [36](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L36): `http://deb.debian.org/debian`
 - Line [37](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L37): `deb http://deb.debian.org/debian/ stretch main non-free contrib\ndeb-src http://deb.debian.org/debian/ stretch main non-free contrib\n`
 - Line [42](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L42): `http://ubuntu.osuosl.org/ubuntu/`
 - Line [43](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L43): `deb http://ubuntu.osuosl.org/ubuntu/ xenial main restricted universe\ndeb-src http://ubuntu.osuosl.org/ubuntu/ xenial main restricted universe\n`
 - Line [53](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L53): `http://ports.ubuntu.com/ubuntu-ports`
 - Line [54](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L54): `deb http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe\ndeb-src http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe\n`
 - Line [59](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L59): `http://deb.debian.org/debian`
 - Line [60](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L60): `deb http://deb.debian.org/debian/ buster main non-free contrib\ndeb-src http://deb.debian.org/debian/ buster main non-free contrib\n`
 - Line [65](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L65): `http://deb.debian.org/debian`
 - Line [66](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L66): `deb http://deb.debian.org/debian/ stretch main non-free contrib\ndeb-src http://deb.debian.org/debian/ stretch main non-free contrib\n`
 - Line [71](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L71): `http://ports.ubuntu.com/ubuntu-ports`
 - Line [72](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L72): `deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe\ndeb-src http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe\n`
 - Line [82](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L82): `http://ports.ubuntu.com/ubuntu-ports`
 - Line [83](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L83): `deb http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe\ndeb-src http://ports.ubuntu.com/ubuntu-ports bionic main restricted universe\n`
 - Line [88](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L88): `http://deb.debian.org/debian`
 - Line [89](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L89): `deb http://deb.debian.org/debian/ buster main non-free contrib\ndeb-src http://deb.debian.org/debian/ buster main non-free contrib\n`
 - Line [94](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L94): `http://deb.debian.org/debian`
 - Line [95](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L95): `deb http://deb.debian.org/debian/ stretch main non-free contrib\ndeb-src http://deb.debian.org/debian/ stretch main non-free contrib\n`
 - Line [100](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L100): `http://ports.ubuntu.com/ubuntu-ports`
 - Line [101](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/slave/manifests/packaging/debian.pp#L101): `deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe\ndeb-src http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe\n`

Script 4: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/rbot/manifests/package.pp
 - Line [22](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/rbot/manifests/package.pp#L22): `wget --directory-prefix=/tmp http://ruby-rbot.org/download/rbot-`

Script 5: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/freight/manifests/init.pp
 - Line [5](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/puppet/modules/freight/manifests/init.pp#L5): `http://build.openvpn.net/debian/freight_team`

Script 6: https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/vagrant/manifests/default.pp
 - Line [15](https://github.com/theforeman/foreman-infra/blob/dc9c632f41900a7ad0c478017bd4853212078662/vagrant/manifests/default.pp#L15): `http://`

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-546](https://cwe.mitre.org/data/definitions/546.html)). Using HTTP without TLS to communicate with other servers/sources gives access to sensitive or security-critical data in cleartext to unauthorized actors during network communication/traffic (e.g., man-in-the-middle attacks).

Configuring HTTP without using TLS in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can instead use HTTPS (HTTP using TLS) to protect the privacy and integrity of the exchanged data. For instance, replace `$auth_url = ‘http://127.0.0.1:35357/’` by `$auth_url = ‘https://127.0.0.1:35357/’`. Thus, you will highly decrease the chances of having your app data leaked.

**Comment by ekohl** [comment]
HTTPS on localhost is nonsense and Debian repos are GPG signed. Only the rbot is actually relevant, but that class is currently actually unused.
