### ISSUE TITLE
Rebuild Koji in new infrastructure and with new architecture

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1435]
Discourse discussion: https://community.theforeman.org/t/rebuilding-koji/20977

Notes:

- Current Koji has server, builder, database all in one machine
- Requires a separate builder to handle EL8 running Fedora
- Is unmanaged by any config management

Server and hostnames layout for new Koji:

- Koji server
  - Hub + database
  - hostname: koji01.aws.theforeman.org
  - service name: koji.theforeman.org
- Koji builders
  - hostname: builder0X.koji.aws.theforeman.org

Additional improvements to consider:
 * Reduce the amount of swap being used [comment](https://github.com/theforeman/foreman-infra/pull/1415#discussion_r472295326)
 * Systemd dependency on mount points [comment](https://github.com/theforeman/foreman-infra/pull/1415#discussion_r472293943)
 * Drop use of /etc/hosts due to floating IP [comment](https://github.com/theforeman/foreman-infra/pull/1415#discussion_r472298280)
 * Get rid of random hostname [comment](https://github.com/theforeman/foreman-infra/pull/1415#discussion_r472301834)
 * Enable SELinux [comment](https://github.com/theforeman/foreman-infra/pull/1415#discussion_r475807780)
 * Add ` /usr/local/bin/foreman-root-restrict.sh` to source control

Action Items:

- [ ] Build out Ansible or Puppet to setup and manage Koji infrastructure
- [ ] Build a new environment with config management on new infrastructure
- [ ] Manage Koji within Foreman instance
- [ ] Migrate to new disk format

**Comment by ekohl** [comment]
Right now the httpd config also breaks on Koji upgrades. That should also be fixed. Don't have a more precise note, but it was noticed during the last upgrade.

**Comment by ekohl** [comment]
On hold due to https://github.com/theforeman/foreman-infra/issues/1795.
