### ISSUE TITLE
Migrate to new ci.centos.org infra on OpenShift

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1473]
see https://lists.centos.org/pipermail/ci-users/2020-July/002098.html and https://docs.fedoraproject.org/en-US/cpe/day_to_day_centos/#_our_workflow

essentially we get an own jenkins controller running on OpenShift and then can do the same things we've been doing on the old ci.centos.org infra (yes, Duffy works ;))

**Comment by ekohl** [comment]
I think we should consider migrating our entire env there, including our nodes. It would save us from having to manage our own controller and possibly avoid the whole "job in our jenkins triggers a job in another jenkins" round trip.

**Comment by ehelms** [comment]
Notes from infrastructure SIG:

Instance has been provisioned at: https://jenkins-foreman.apps.ocp.ci.centos.org

Action Items:

- [ ] Run test jobs on new Jenkins [@evgeni]
- [ ] Try connecting an external node to the new Jenkins

Open Questions:

- [ ] Can we add a friendlier domain name to the new Jenkins instance?
- [ ] How stable will this new instance be compared to the old instance?
