### ISSUE TITLE
Document old Debian release archival procedure

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1666]
The process to move releases from https://deb.theforeman.org/ to https://archivedeb.theforeman.org/ needs to be documented.

**Comment by ehelms** [comment]
Notes from infrastructure SIG:

Discussion thread on discourse: https://community.theforeman.org/t/archiving-old-debian-ubuntu-releases/20540

Action Items:

- [ ] Add to release procedure to archive N-5 version [@evgeni]

**Comment by evgeni** [comment]
note: make a step in the release proces "open an issue in foreman-infra to archive" so that the release owner doesn't have to do it (as the plate during release is full)

**Comment by evgeni** [comment]
documentation:
- https://github.com/theforeman/foreman-packaging/pull/10882

procedure:
- https://github.com/theforeman/foreman-infra/issues/1666
