### ISSUE TITLE
Rename node01.conova.t.o to virt01.conova.t.o

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1667]
The name node01 is confusing since we use the same name for our Jenkins nodes. The name virt01 is clearer.

* [x] Create new DNS entry
* [x] `hostnamectl set-hostname virt01.conova.theforeman.org`
* [x] Rename in Foreman
* [x] Cycle Puppet certificate
* [x] Remove old DNS entry

**Comment by ehelms** [comment]
I know some work was done in this area, could the issue get updated with what action items have been completed?

**Comment by evgeni** [comment]
no work has been done

**Comment by ekohl** [comment]
Work has been completed.
