### ISSUE TITLE
Allow building on RHEL in our Koji setup

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1670]
We should contact Red Hat to see if RHEL for Open Source Infrastructure can be used by the Foreman project to build RPMs in our Koji setup.

**Comment by ehelms** [comment]
Notes from infrastructure SIG:

* 200 subscriptions by default, can be extended
* Supported installation OSes
  * Depends on where we land on what we build on: RHEL, a downstream variant
  * Communicate that it should work, but we are not choosing to test on it today

* Three parts:
    * Building in Koji against RHEL (are we allowed to host the RHEL repos under ROSI?)
       * RHEL repositories can be added to Koji for building but not exposed publicly for consumption by users 
    * Testing in CI for user support
    * Running Foreman infrastructure on RHEL

* Long Term Goal:
    * Build on RHEL 8
    * Test against CentOS 8 Stream
    * Test on RHEL 8
    * Support implicitly RHEL clones

* How does this work for RHEL 9? And the beta?

Action Items

- [ ] Setup a dedicated discussion meeting around this topic

**Comment by ehelms** [comment]
Adding a link to the RFC post for discussion from discourse: https://community.theforeman.org/t/rfc-enterprise-linux-8-and-9-support/26282

**Comment by ehelms** [comment]
Notes from 12/8/2021:

- The view is users want compatibility so we should choose option 1 and build against RHEL.
- How do we access and pull the RHEL content into our Koji?
  - We could spin up a special host to just host the RHEL content
  - This host would be locked down network access wise
- Mock would not have access to the RHEL repositories
  - Could use it against stream repositories
  - Could maybe use UBI containers with their repositories?

Next Steps

- Report back to community thread the direction
- Build out a plan of action and steps for how we will integrate the RHEL repositories into our build environment

**Comment by evgeni** [comment]
we need baseos, appstream and crb repos.

**Comment by evgeni** [comment]
note to myself, it seems a rhel8 box on amazon using rhui only has access to rhel8 content, so we'd need to sub to a "real" account to get all the things :)

**Comment by evgeni** [comment]
asked the right people to get us some subs, now waiting
