### ISSUE TITLE
Update Foreman to 3.6

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1676]
Foreman's current version is outdated and needs to be updated to the latest release.

**Comment by ekohl** [comment]
Should be done as part of #1686

**Comment by evgeni** [comment]
- update puppet modules
- stop services
- update foreman
- db stuff

**Comment by ekohl** [comment]
> update puppet modules

https://github.com/theforeman/foreman-infra/pull/1831

> * stop services
> 
> * update foreman
> 
> * db stuff

We are now running version 3.6.1.
