### ISSUE TITLE
Move prprocessor to shared infrastructure

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1679]
The [prprocessor](https://github.com/theforeman/prprocessor) project handles a number of tasks for the project and currently runs on @ekohl own infrastructure.

Options to move to:

- OSCI Openshift: https://openshift-console.osci.io

Action Items

- [x] Move to Python 3.7
- [x] Move to one of the shared infrastructure environments
- [ ] Make a post to discourse introducing Prprocessor to community again since it's been a while and new developers may not be familiar with it [@ekohl]

**Comment by ekohl** [comment]
I've moved back to Python 3.7 (or really 3.8) compatibility (https://github.com/theforeman/prprocessor/commit/d6eae43745cbf78067c2b8ee8c5d58cde8d9e7c3). Then I added compatibility with s2i (https://github.com/theforeman/prprocessor/commit/1e6fa6961c65006eef39a25e2cd12e9a4a4e1fc8) and documented (https://github.com/theforeman/prprocessor/commit/4ec7fb4b3a63f84e92a997a4782f47ea4b44ac1b).

Now I've switched the URL (at https://github.com/organizations/theforeman/settings/apps/pr-processor) and it's serving from OpenShift. If there is a need to switch back, change the URL to https://prprocessor.ekohl.nl/ which I'll keep running for a while.

At least in https://github.com/theforeman/prprocessor/pull/172 I verified that the webhook delivery works, though that doesn't call back to Redmine. However, it'd surprise me if that's broken.

Now I'll make a post on Discourse to announce the migration. With that I think we should monitor this for a week or so and then consider this resolved.

One thing I couldn't get working was triggering builds after a GitHub push. Probably better to open a new issue for that.

**Comment by ekohl** [comment]
Oh, and running it on HTTPS instead of plain text HTTP

**Comment by evgeni** [comment]
I've added the following to the openshift route definintion:

```yaml
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
```

and HTTPS works now.

**Comment by ekohl** [comment]
Thanks for that! I switched the URL back to openshift and monitor it for a bit. Then I can make a Discourse post to announce it.

**Comment by evgeni** [comment]
I've flipped the webhook in https://github.com/theforeman/prprocessor/settings/hooks from using the "github" hook URL in openshift, to the "generic" one, and now push events to the repo trigger new deployments.

(didn't have the motivation to debug *why* the github specific one didn't work)

**Comment by ekohl** [comment]
I made an announcement here: https://community.theforeman.org/t/prprocessor-migrated-to-osci/28148

Perhaps the one item (do a more generic introduction) is still open, but it may be better to capture that in a new issue so we can close this one out.

**Comment by ekohl** [comment]
I've opened https://github.com/theforeman/foreman-infra/issues/1733 and now consider this as done. Thanks @evgeni for fixing the 2 issues I didn't get around to.

I'll leave the instance on my personal infra running for a while. If there are issues, it should be easy to roll back.
