### ISSUE TITLE
Update Redmine and move to new infrastructure

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1681]
Current Redmine version: 3.Y
Current infrastructure: Scaleways
Codebase: https://github.com/theforeman/redmine

Migration options:

- OSUOSL
- Conova box
- OSCI Openshift (https://openshift-console.osci.io)

Action Items

- [x] Build migration plan and document here
- [x] Move Redmine to new infrastructure
- [x] Test Redmine upgrade locally
- [x] Upgrade Redmine to 5.Y

**Comment by evgeni** [comment]
@ehelms is thinking about moving redmine to github instead :)

**Comment by ekohl** [comment]
It should be noted the boot method our VM now uses has been EOL since May and we're at risk of losing it. https://www.scaleway.com/en/docs/compute/instances/troubleshooting/bootscript-eol/ explains how to move away from it, but we should just migrate one time and that is to a new VM.

**Comment by ehelms** [comment]
I think our two options are:

 * VM on Conova box if there is resources available on it still
 * Running it via OSCI Openshift

**Comment by evgeni** [comment]
To summarize the events so far:
- I have rebased our patches ontop of Redmine 5.0.5 (you can find the "deployable" result in https://github.com/theforeman/redmine/tree/new-redmine and a "clean" patchset at https://github.com/theforeman/redmine/tree/5.0.5%2Btfm)
- ensured the plugins we use get Redmine 5 support (so far, in our forks, will see to get that upstream later)
- tried redmine on OpenShift of OSCI and hit two snags:
  - no good way to provision custom SSL certs -- this can be workarounded by fronting Redmine with Fastly
  - no way to mount PersistentVolume in shared mode (K8s/OS can do that, but the storage at OSCI apparently not), which makes it impossible to run a "update repos" cronjob in a separate container
- spun up a small CentOS Stream 9 VM at conova and deployed redmine there instead (Apache, Puma, Systemd)
- the instance is available under https://projects-test.theforeman.org

What needs to happen now:
- define a date when we switch over
- lower DNS TTL for projects.theforeman.org
- stop apache on redmine01.theforeman.org
- create a fresh backup using restic (`systemctl start restic-backup@redmine`)
- restore said backup on redmine01.conova (see below)
- flip DNS

Restore process:
```
$ restic restore latest --include /var/lib/redmine/redmine.backup.sql.gz --target /tmp/redmine
[root@redmine01 ~] mv /tmp/redmine/var/lib/redmine/redmine.backup.sql.gz /tmp
[postgres@redmine01 ~]$ zcat /tmp/redmine.backup.sql.gz | sed 's/adminpz8bn8d/redmine/g' | psql redmine
[redmine@redmine01 ~]$ bundle exec rake db:migrate RAILS_ENV=production

$ restic restore latest --include /var/lib/redmine/files --target /tmp/redmine
[root@redmine01 ~]# chown -R redmine:redmine /tmp/redmine/var/lib/redmine/files/
[root@redmine01 ~]# mv /tmp/redmine/var/lib/redmine/files/ /var/lib/redmine/
[root@redmine01 ~]# restorecon -Rvn /var/lib/redmine/files/
```

**Comment by evgeni** [comment]
Note: the same box also runs the (old) prprocessor.theforeman.org, which is not part of the above migration and thus we can't shut down the old box *just yet*

**Comment by evgeni** [comment]
Note2: I totally forgot that I setup the box as v6 only, as we don't have v4 left at conova.

**Comment by ekohl** [comment]
I've started to look at replacing the legacy PR processor. https://github.com/theforeman/prprocessor/pull/177 is one step. There are more things.

Closing inactive PRs could possibly be replaced by stalebot in a per-repo config.

Listing the repos (as used by Redmine sync) could be replaced by retrieving the repo and reading the config directly.

**Comment by evgeni** [comment]
I have updated the TTL of `projects.theforeman.org` to 300 (the minimum our DNS provider supports) and propose to do the switch next week, either Monday or Tuesday in the CEST morning.

**Comment by evgeni** [comment]
> Closing inactive PRs could possibly be replaced by stalebot in a per-repo config.

how many repos use that feature anyway? according to https://github.com/theforeman/prprocessor/blob/master/config/close_inactive.yaml only `@theforeman/foreman`, so it's pretty "cheap" to replace it with stalebot

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman/pull/9828

**Comment by ekohl** [comment]
> I've started to look at replacing the legacy PR processor. [theforeman/prprocessor#177](https://github.com/theforeman/prprocessor/pull/177) is one step. There are more things.

https://github.com/theforeman/foreman/pull/9826 is also related.

**Comment by ekohl** [comment]
As for the PR processor, my plan is to:
* Merge https://github.com/theforeman/prprocessor/pull/179
* Finish https://github.com/theforeman/prprocessor/pull/177
* Finish https://github.com/theforeman/prprocessor/pull/178

Then it should only remain to link and post a message on merge conflicts, as well as the list of repositories used in the cronjob. It won't be done by then, but I'd consider it a big milestone. Keeping the old service running would give us an easy path to revert in the next few days.

**Comment by ehelms** [comment]
> I have updated the TTL of `projects.theforeman.org` to 300 (the minimum our DNS provider supports) and propose to do the switch next week, either Monday or Tuesday in the CEST morning.

Leeeeerooooy :fireworks: :fireworks:

**Comment by ekohl** [comment]
Given this is resolved, let's close it. Then open a new issue to decommission the old box. I've started https://github.com/theforeman/foreman-infra/issues/1919 but please add anything I may have missed.
