### ISSUE TITLE
Migrate Jenkins off of Rackspace

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1684]
The Jenkins (https://ci.theforeman.org) needs to be moved off of Rackspace infrastructure and on to one of our other providers. 

Naming info:

- hostname: controller01.jenkins.conova.theforeman.org
- servicename: ci.theforeman.org

Action Items

- [x] Discuss if we could and want to just use new Jenkins running on Openshift at ci.centos.org
- [x] If keeping our own Jenkins
  - [x] Create new machine
  - [x] Add it to Foreman
  - [x] Assign hostgroup
  - [x] Take an outage window
    - [x] Mark nodes in maintenance mode
    - [x] Sync over /var/lib/jenkins
    - [x] Take all but one node out of maintenance node on old Jenkins
  - [x] Turn on new Jenkins
    - [x] Turn on one node
  - [x] Run test job -- nightly pipeline
  - [x] Pick a switchover date
    - [x] Target Date: Sometime before Foreman branching
    - [x] Lower TTL day or two before target date
    - [x] Update DNS

**Comment by ekohl** [comment]
I've created a new machine on our Conova virt host. It runs on CentOS Stream 9, meaning we won't be affected by CentOS 7 & 8 Stream EOL next year.

On Thursday I'd like to perform the migration. Announcement on https://community.theforeman.org/t/jenkins-migration-on-2023-03-23/32860.

**Comment by ekohl** [comment]
Status update:

* https://github.com/theforeman/foreman-infra/pull/1837 adds EL9 support for the JJB required module
* https://github.com/voxpupuli/puppet-jenkins/pull/1069 is needed to install the latest Jenkins version
* https://github.com/theforeman/foreman-infra/pull/1835 makes it easier to test Hiera in Vagrant

**Comment by ekohl** [comment]
I just migrated it: https://community.theforeman.org/t/jenkins-migration/33317
