### ISSUE TITLE
Migrate Puppetserver to stand-alone instance

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1685]
Today, the Foreman instance has a Puppetserver on board. This aims to move the Puppet server to it's own virtual machine.

Naming:

- Hostname: `puppet01.<provider>.theforeman.org`
- Servicename: puppet.theforeman.org

Action Items

- [x] Create new virtual machine on a provider
- [ ] ??

**Comment by ekohl** [comment]
I've created `puppet01.conova.theforeman.org` (for now IPv6-only) with CentOS 8 Stream. The ran:
```sh
dnf install https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
dnf install puppetserver
. /etc/profile.d/puppet-agent.sh
puppetserver ca setup --ca-name 'Foreman Puppet CA' --certname puppet.theforeman.org --subject-alt-names puppet.theforeman.org,$HOSTNAME
puppet config set --section agent server puppet.theforeman.org
systemctl enable --now puppetserver puppet
firewall-cmd --add-port 8140/tcp
firewall-cmd --permanent --add-port 8140/tcp
```

Now I'm going to set up a new Foreman server too and set that up. Then we can migrate nodes. Though I do think we should consider recreating all our Jenkins nodes as EL8 in our new infra.

**Comment by ekohl** [comment]
In https://github.com/theforeman/foreman-infra/pull/1777 there's the real migration plan. This is now resolved.
