### ISSUE TITLE
Replace exim Puppet module (or exim)

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1692]
We currently have our own exim puppet module that could break in the future with newer operating systems. Moving to a shared puppet module may have a longer and better support life.

**Comment by ehelms** [comment]
Infrastructure SIG notes:

- Nothing is currently broken, so low priority
- We could replace exim with postfix given that is the default in EL

**Comment by evgeni** [comment]
Should probably be handled while upgrading/migrating to EL8 by moving to Postfix
