### ISSUE TITLE
move EL Jenkins nodes to EL9

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1706]
currently we have a mixture of CentOS and RHEL 7 machines
let's standardize on CentOS 8 Stream

**Comment by ekohl** [comment]
When replacing this, keep https://github.com/theforeman/foreman-infra/issues/1692 in mind and migrate it to postfix.

**Comment by evgeni** [comment]
blocked by:
- [ ] https://github.com/theforeman/foreman-infra/pull/2071
- [ ] https://github.com/theforeman/foreman-infra/issues/2021

**Comment by evgeni** [comment]
node11 and node12 at OSUOSL are EL9 nodes and Smart Proxy (Ruby) and Packaging (Python) seems to work fine.

**Comment by evgeni** [comment]
- node03.conova and node03.netways were deployed as "fast" nodes, and all known issues fixed.
- node02.conova and node02.netways are deleted from foreman and dns and powered down, will delete the VMs in a few days

**Comment by evgeni** [comment]
VMs removed, storage removed.

calling this done.
