### ISSUE TITLE
Need a new owner for Discourse

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1709]
they will need to take care of upgrades (or automate these)

**Comment by upadhyeammit** [comment]
I would like to own this, request to provide necessary permissions on host and discourse to manage it.
Thanks!

**Comment by evgeni** [comment]
today, part of the discourse migration, I also performed the following changes:
- the `discourse@t.o` email alias that was pointing at greg, now points to @ekohl @nofaralfasi and myself
- the `admins` group now contains only the following people: @ekohl @nofaralfasi @ehelms @ares and myself

Eric, Marek, do y'all also want to be added to the mail alias? it's mostly update notifications

I would consider Nofar, Ewoud and myself the new "owners" of the service and close this ticket out with it.

**Comment by evgeni** [comment]
(closing, given the thumbs up from the involved people)
