### ISSUE TITLE
Migrate Discourse off of Scaleway VM

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1710]
while doing so, deploy on a newer OS than Debian 9

**Comment by ekohl** [comment]
And consider increasing its memory from 2GB to more. See https://community.theforeman.org/t/added-a-swapfile-on-discourse01/30665 as well.

**Comment by ekohl** [comment]
It should be noted the boot method our VM now uses has been EOL since May and we're at risk of losing it. https://www.scaleway.com/en/docs/compute/instances/troubleshooting/bootscript-eol/ explains how to move away from it, but we should just migrate one time and that is to a new VM.

**Comment by evgeni** [comment]
## preparation

- [ ] create a new `discourse01.conova.theforeman.org` VM (4+GB RAM, 4 CPU): CentOS Stream 9
- [ ] install Docker (it's the only [supported deployment method](https://github.com/discourse/discourse/blob/main/docs/INSTALL.md)): https://docs.docker.com/engine/install/centos/
- [ ] restore backup and see if things work OK

## migration

- [ ] define a date when we switch over
- [ ] lower DNS TTL for community.theforeman.org
- [ ] create a fresh backup
- [ ] restore said backup on discourse01.conova
- [ ] flip DNS

## things to consider

- https://meta.discourse.org/t/enable-a-cdn-for-your-discourse/14857
- https://meta.discourse.org/t/restore-a-backup-from-the-command-line/108034

**Comment by evgeni** [comment]
An restore from tonight's backup is running at https://discourse01.conova.theforeman.org/

Unless people yell, I'll flip to that instance (after refreshing the restored data) tomorrow.

**Comment by evgeni** [comment]
After talking to Ewoud on IRC: let's rather migrate today, so we have tomorrow to fix things, instead of a weekend.

**Comment by evgeni** [comment]
And done (couldn't get it done yesterday as the RAM upgrade to virt01.conova happened)
