### ISSUE TITLE
Update Discourse to 2.8.8

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1732]
Currently we're running version 2.8.0.beta10. It should also update the various plugins, which should fix https://community.theforeman.org/t/events-calender-ical-link-no-longer-working/24350/24 (remember to post an update there once it's been done).

**Comment by ekohl** [comment]
I modified `/var/lib/discourse/containers/app.yml` to point to the stable version, rather than the default (`tests-passed`). Stable is currently 2.8.8.

**Comment by evgeni** [comment]
we're on 3.0.2 now; https://community.theforeman.org/t/discourse-updated-to-3-0-2/33119
