### ISSUE TITLE
Automation of packaging bumping dependencies

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1755]
Follow on from the work done by https://github.com/theforeman/foreman-infra/issues/1693 

The goal is to add automatic bumping of dependencies of Foreman within packaging. This needs to take into consideration that we cannot blindly bump dependencies but need to consider which versions are appropriate from something like Gemfile.lock.

**Comment by ehelms** [comment]
I got inspired by latest Infra SIG meeting and opened a PR to tackle this for RPMs:

 - https://github.com/theforeman/foreman-packaging/pull/8039

**Comment by evgeni** [comment]
The automation works (the results need to be reviewed, but that's out of scope) = done
