### ISSUE TITLE
move centos jenkins usage over to jenkins-foreman.apps.ocp.cloud.ci.centos.org

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#1800]
should be just a matter of changing urls and re-creating the api token for the jenkins user

for details see https://lists.centos.org/pipermail/ci-users/2022-December/004630.html

**Comment by ekohl** [comment]
Do we want to consider concentrating everything in our own Jenkins now that Duffy is a public API?

**Comment by evgeni** [comment]
That is also a possibility, yes

**Comment by ekohl** [comment]
https://lists.centos.org/pipermail/centos-devel/2023-January/142737.html was sent as a reminder. The deadline is end of March.

**Comment by evgeni** [comment]
done
