### ISSUE TITLE
Close Rackspace account

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-infra#1843]
The servers are turned off, but they still exist right now. They can be deleted and then the account needs to be closed.

**Comment by ekohl** [comment]
Servers have been deleted. @ares please do the work to close the account.

**Comment by ehelms** [comment]
@ares Has the account been closed?

**Comment by ekohl** [comment]
No, but we found out we still use Mailgun to send email. Thanks for the reminder to revisit https://github.com/theforeman/foreman-infra/pull/1849.
