### ISSUE TITLE
Replace RVM on Jenkins nodes

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#2021]

**Comment by ehelms** [comment]
See https://github.com/theforeman/foreman-infra/pull/2016 for discussion that sparked this issue

**Comment by evgeni** [comment]
https://github.com/theforeman/jenkins-jobs/pull/445 "replaced" the usage of rvm with rbenv.
Is cleanup in scope for this? Or shall we just dump rvm from puppet and clean up by re-deploying on EL9?

**Comment by evgeni** [comment]
found one more use https://github.com/theforeman/jenkins-jobs/pull/452

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-infra/pull/2070

**Comment by evgeni** [comment]
I've dropped RVM from Puppet and would consider this topic complete now.
(RVM is still installed on the EL8 CI nodes, but unused and they will be rotated soon to EL9 based ones: #1706)
