### ISSUE TITLE
Move repoclosure to use Alma repositories

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#2085]
Needs changes to:

- foreman-packaging
- pulpcore-packaging
- candlepin-packaging

Include backporting to at least 3.10 for Foreman. 

https://github.com/theforeman/foreman-packaging/pull/10514

**Comment by evgeni** [comment]
@ekohl I'd say this is now done, right?

**Comment by ekohl** [comment]
With Pulpcore picks merged, yes
