### ISSUE TITLE
Add Alma to puppet modules

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#2087]
This will need to add Alma to the puppet module metadata to start testing it rather than CentOS 8 stream. And update puppet_metadata dependency.

**Comment by ekohl** [comment]
List of our supported modules: https://github.com/theforeman/foreman-installer-modulesync/blob/master/managed_modules.yml

For each module, make sure we list AlmaLinux 8 & 9.

Then we also want to update to puppet_metadata `~> 4.0`, which automatically skips CentOS Stream 8 in CI. That can be done here:
https://github.com/theforeman/foreman-installer-modulesync/blob/077114650945df080132f88e802383592e423758/config_defaults.yml#L23-L24

**Comment by archanaserver** [comment]
Another list of PRs, about updating `puppet_metadata to ~> 4.0` and `voxpupuli-acceptance to ~> 3.0` to all managed modules.
- [x] https://github.com/theforeman/puppet-foreman/pull/1169
- [ ] https://github.com/theforeman/puppet-candlepin/pull/265
- [ ] https://github.com/theforeman/puppet-certs/pull/455
- [ ] https://github.com/theforeman/puppet-foreman_proxy/pull/841
- [ ] https://github.com/theforeman/puppet-dhcp/pull/235

**Comment by archanaserver** [comment]
the rest 3 PRs  needs review, 
https://github.com/theforeman/puppet-pulpcore/pull/347
https://github.com/theforeman/puppet-dns/pull/254
https://github.com/theforeman/puppet-dhcp/pull/234

**Comment by archanaserver** [comment]
@ekohl @ehelms to close this issue, only this one needs a final review i believe.
https://github.com/theforeman/puppet-pulpcore/pull/347
