### ISSUE TITLE
Switch selinux projects to Alma

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#2089]
- katello-selinux
- foreman-selinux

**Comment by ekohl** [comment]
We'll need to update https://github.com/theforeman/foreman-selinux/blob/develop/.github/workflows/compile.yaml and https://github.com/theforeman/katello-selinux/blob/master/.github/workflows/tests.yml.

I'd like to continue testing on CentOS 9 Stream, but also add AlmaLinux 8 & 9 to the testing matrix.
