### ISSUE TITLE
Update the SELinux Puppet module used

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#466]

**Comment by evgeni** [comment]
I will try to look into this after talking to @mmoll

**Comment by mmoll** [comment]
Just to clarify, this is about the module in `puppet/modules/selinux`, which is st the moment at 0.8.x and I didn't update it to 1.0 and further, because 0.8 -> 1.0 has breaking changes, which require updates on our side.

At the end, we need to be on the latest 1.x release.
