### ISSUE TITLE
Migrate Puppetmaster to EL7

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#467]
We're getting a VM from ovirt.org for that. foreman-installer in addition to the current Puppet self-managing would be good, The current Puppet CA expires in August 2018.

**Comment by mmoll** [comment]
Blocked until we can access the VM from the oVirt people.

**Comment by ekohl** [comment]
https://ovirt-jira.atlassian.net/browse/OVIRT-1484

**Comment by mmoll** [comment]
We're going to use a new Rackspace node, now that the new Jenkins slaves at OSUOSL are up and running Rackspace slaves will be cut down.

**Comment by ekohl** [comment]
I believe this is done now. Sadly moving things on the board doesn't actually close it.
