### ISSUE TITLE
Migrate Jenkins master to EL7

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#470]

**Comment by ekohl** [comment]
Initially we wanted to run this on ovirt.org infra but now that it's rejected, should we rebuild it on rackspace for now?

**Comment by mmoll** [comment]
We can think about that, but this is IMHO low prio, as we're having Java 8 avaible also on CentOS 6.

**Comment by ekohl** [comment]
The current annoying thing is that JJB is running on python 2.6 and the latest version need 2.7. That means we should run JJB on a slave, upgrade the master or use an SCL.

**Comment by mmoll** [comment]
I see...

As /var/lib/jenkins is a separate volume, it should be quite easy to just rebuild the VM with CentOS 7, re-mount the volume and run Puppet to do the rest.

**Comment by ehelms** [comment]
In either case I think we should run jjb on a slave to get immediate turn
around and observability of job generation rather than waiting some time
window for puppet.

**Comment by ekohl** [comment]
This is now done.
