### ISSUE TITLE
Many tests failing on *ABORTED*

### ISSUE THREAD

**Issue by dLobatog** [theforeman/foreman-infra#490]
There are many PR test runs on foreman_remote_execution / foreman_ansible (which also runs REX tests) which fail with ABORTED after 2h of running tests. I wonder if there's any plan to attack this (at the dev level I don't think we are working on this technical debt.

**Comment by mmoll** [comment]
theforeman-el7-vm0{1,2}.phx.ovirt.org are too slow to finish some tests in the 2h window. I can remove the Jenkins "fast" from them, but then all those jobs will queue more on the remaining fast slaves.

**Comment by ehelms** [comment]
We could bump to 3 hours and continue to monitor. I worry that a test suite exists that can't finish in under 2 hours even on slower hardware.

**Comment by mmoll** [comment]
I think this got resolved in the meanwhile :tada:
