### ISSUE TITLE
stop using schedule-failed-build plugin

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#491]
The plugin is [deprecated](https://wiki.jenkins.io/display/JENKINS/Retry+Failed+Builds+Plugin) and has not seen an [upstream commit since 2012](https://github.com/jenkinsci/schedule-failed-builds-plugin).

Options:
* [Naginator Plugin](https://wiki.jenkins.io/display/JENKINS/Naginator+Plugin)
* [Periodic Reincarnation Plugin](https://wiki.jenkins.io/display/JENKINS/Periodic+Reincarnation+Plugin)

**Comment by evgeni** [comment]
One question that arises is: do we even use this plugin now? I know it's referenced in the jobs, but I could not find any occurrence of it actually re-scheduling a failed job.

**Comment by ekohl** [comment]
Let's try to get rid of it altogether. For CI it doesn't make sense and master builds are probably covered by nightly runs anyway.
