### ISSUE TITLE
update signing key for deb.theforeman.org

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-infra#553]
```
pub   4096R/6F8600B9563278F6 2016-04-08 [expires: 2018-04-08]
      Key fingerprint = AE0A F310 E2EA 96B6 B6F4  BD72 6F86 00B9 5632 78F6
uid                          Foreman Automatic Signing Key (2016) <packages@theforeman.org>
sub   4096R/96EBC6F06F1B04B4 2016-04-08 [expires: 2018-04-08]
```

the key should be either rotated or the expiry should be bumped

**Comment by ChristophBerg** [comment]
+1 on extending the lifetime, that would make things easier for people who have coded the key ID into their puppet manifests, etc.

**Comment by mmoll** [comment]
I did extend the expiration date, please check.

**Comment by mmoll** [comment]
Seems to work perfectly fine. People who did import the key before the expiration extension need to refresh it.
